### PR TITLE
Added securitytrails api historical records

### PR DESCRIPTION
**Pull request by zorox0x**
Implemented a SecurityTrails API historical records function that retrieves historical IP information from SecurityTrails. Additionally, introduced a feature to generate a configuration file (`config.ini`) for users to input their API key if not already present.

Upon initial execution of the script, it generates a `config.ini` file with the following content:

```ini
[DEFAULT]
securitytrails_api_key = your_api_key
```

Subsequently, the script attempts to retrieve data from the SecurityTrails API. If the retrieval fails due to reasons such as quota limitations or site unavailability, the corresponding function is gracefully skipped.

Please ensure to include information about the configuration file in the README.md file.

### CODE REVIEW

**Comment by thisisshubhamkumar** [comment]
Hey fantastic work once again but while I was testing I found it is completely ignoring Historical IP Addresses by ViewDNS

**Comment by thisisshubhamkumar** [comment]
It seems that your old code for ViewDns is no longer functional, possibly due to changes in the website's structure. Your current code, on the other hand, seems to be working fine.

**Comment by thisisshubhamkumar** [comment]
As this is your code, you can take a look to see if scraping is still possible. I might try using either Selenium or Pyppeteer. Alternatively, I was considering using the ViewDNS API as they offer a better free API quota compared to SecurityTrails.

We can attempt to scrape the data, and if that method fails, we can use the ViewDNS API.

**Comment by zorox0x** [comment]
image

ViewDns funcution works fine for me.

**Comment by thisisshubhamkumar** [comment]
Upon retesting, it seems that either my IP was blocked or the rate limit and maximum request quota were exceeded. However, switching my IP or using a VPN/Proxy works fine.

**Comment by zorox0x** [comment]
I don't recommend using selenium.
If necessary, I will integrate the ViewDNS API.

**Comment by thisisshubhamkumar** [comment]
Okay, sure! First, I am going to merge this PR once I reach home.

Thanks for your valuable contribution. By the way, I came across an article on Kitploit titled "Top 20 Most Popular Hacking Tools in 2023."

Our tool CloakQuest3r is there. https://www.kitploit.com/2023/12/top-20-most-popular-hacking-tools-in.html

Also, I am trying to improve subdomain scan. Should we ask the user to provide a wordlist as a command line argument, or should we use a bigger and better subdomain wordlist? Any recommendations?

**Comment by zorox0x** [comment]
It is recommended to prompt users for their custom wordlist. Additionally, incorporating an option for users to supply their own list of subdomains would enhance the tool's flexibility.

**Pull request merged**
